name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: echo $PATH
      shell: bash
    - id: step2
      run: echo "::set-output name=test::world"
    - uses: actions/checkout@v3
    - name: Display the path
    
